name: Manual Run Web Tests Tag and browser
run-name: Manual - Web Tests Run Tag and browser

on:  
  workflow_dispatch:
      inputs:
        tag:
          type: string
          description: Qual é a TAG a ser executada?
          required: true
        
        browser:
          type: choice
          description: 'Qual Browser a ser executado?'
          required: true
          default: 'chromium'
          options:
          - chromium
          - firefox
          - webkit

jobs:
  web-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Node Js
        uses: actions/setup-node@v4

      
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test
          sudo npx playwright install-deps
          rfbrowser init

      - name: Run Web Tests
        run: |
          robot -d ./results -v HEADLESS:true -v BROWSER:${{ inputs.browser }} -i ${{ inputs.tag }} tests

      - name: upload test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results${{ inputs.browser }}
          path: ./results
          # if-no-files-found: ignore
          retention-days: 2
      
      - name: Download results
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: results${{ inputs.browser }}

      - name: Send Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.4
        with:
          report_path: ./results
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: true

      - name: Rename report File to index for gh-pages
        run: |
          mv ./results/report.html ./results/index.html

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./results