name: Run Web with Allure Report

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    permissions: write-all


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Node Js
        uses: actions/setup-node@v4

      
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test
          sudo npx playwright install-deps
          rfbrowser init

      - name: Prepare Allure history # Step to prepare Allure history directory
        run: |
          cd ..
          mkdir -p allure_results

      - name: Run Web Tests
        run: |
          robot --listener allure_robotframework -v HEADLESS:true tests

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
  
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
            gh_pages: gh-pages
            allure_history: allure-history
            allure_results: allure_results
            allure_report: allure-report
  
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history