name: Run Web with Allure Report

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    permissions: write-all


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Node Js
        uses: actions/setup-node@v4

      
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test
          sudo npx playwright install-deps
          rfbrowser init
      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
          tar -zxvf allure-2.13.8.tgz
          sudo mv allure-2.13.8 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          
      - name: Run Test
        run: robot --listener "allure_robotframework;output/allure-results" -v HEADLESS:true tests/ || true

      - name: Generate report
        run: allure generate output/allure-results -o allure-report --clean

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
  
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
            gh_pages: gh-pages
            allure_history: allure-history
            allure_results: allure-results
            allure_report: allure-report
  
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history