name: Run Web with Allure Report

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    permissions: write-all


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure Node Js
        uses: actions/setup-node@v4

      
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test
          sudo npx playwright install-deps
          rfbrowser init

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
          tar -zxvf allure-2.13.8.tgz
          sudo mv allure-2.13.8 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
  
      - name: Clean output allure
        run: rm -rf output/

      - name: Run Test
        run: robot -d logs --listener "allure_robotframework;output/allure-results" -v HEADLESS:true tests/ || true

      - name: Generate report
        run: allure generate output/allure-results -o allure-report --clean

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          
  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - web-tests
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://edgarmsilva.github.io/playwright-robotframework/index.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: allure-report
          path: allure-report/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4